### ISSUE TITLE
NPC page of tab is empty after enabled on Cacti 1.2.21

### ISSUE THREAD

**Issue by hinchoi** [Cacti/plugin_npc#12]
Describe the bug
NPC page of tab is empty after enabled on Cacti 1.2.21, but all the configuration has been succeeded configured.

1. Go to 'tab of NPC'
2. see empty page with blank.

**Expected behavior**
It should have dashboard come out.

**Screenshots**
![image](https://user-images.githubusercontent.com/29793380/170391779-32d0d7d1-649f-4678-b39d-dc0af910d997.png)

**Plugin (please complete the following information):**
 - Version: 
	cacti 1.2.21
	centos 7.9
	php 7.3.33
	mariadb 10.4.25
	nagios 4.4.6
	apache 20120211
	json version	1.7.0
        ndoutils 2.1.3
 - Source: [https://github.com/Cacti/plugin_npc/]
 - Browser:
   Chrome [Version 101.0.4951.54 (Official Build) (64-bit)]
   firefox Version 100.0.2
   opera  Version:86.0.4363.59

**Comment by TheWitness** [comment]
Look at the browser debug console.  You may have "unsafe javascript" calls being executed.  There is a setting to get you past those.  Under `Console > Configuration > Settings > General`.

**Comment by hinchoi** [comment]
Dear Engineer

I have followed your step to debug the npc plugin as below graph shown, but I didnot see any specific logs. please comment. Appreciated for your advice. thanks.

![image](https://user-images.githubusercontent.com/29793380/170412146-dba8a86c-72d8-4f2b-9991-0549667c271c.png)
![image](https://user-images.githubusercontent.com/29793380/170412188-589b086c-87da-451c-9bf0-0f8da82b97af.png)

**Comment by hinchoi** [comment]
Here from chrome browser debug console:
![image](https://user-images.githubusercontent.com/29793380/170413701-5ce1cc44-118e-46ee-a530-342daa585386.png)

**Comment by hinchoi** [comment]
issue has been resolved, thanks.
![image](https://user-images.githubusercontent.com/29793380/170444374-78d12c41-d494-4f8c-b6bb-760c1c3f1817.png)
