### ISSUE TITLE
Nagios sync partially to NPC plugin - only  can see update of hostgroup

### ISSUE THREAD

**Issue by hinchoi** [Cacti/plugin_npc#13]
Dear Cacti engineer,

I'm facing the following issue, need your expertized advice. Much appreciated for your feedback and comment. Thank you.

**Describe the bug**
Nagios sync partially to NPC plugin - only  can see update of hostgroup

**Steps to reproduce the behavior:**
Go to 'tab of NPC'
only see the hostgroup 1 host up, no update to host status  and service status summary

**Expected behavior**
It should have appearance 1 host up at host status summary and service status summary

**Screenshots**

from NPC dashboard:
![image](https://user-images.githubusercontent.com/29793380/174206508-7c4f81f4-0d93-45ec-8f8b-227919257d89.png)

from nagios status:
![image](https://user-images.githubusercontent.com/29793380/174206623-64b83318-3d29-428c-9401-d690c89b70ac.png)
![image](https://user-images.githubusercontent.com/29793380/174206657-bd80a71f-140c-4e16-9456-fa01eaaa803f.png)
![image](https://user-images.githubusercontent.com/29793380/174206707-5a5f6a75-d112-4365-967e-27c4f51a1c2c.png)

**Nagios logs:**
![image](https://user-images.githubusercontent.com/29793380/174206875-5522ea2d-4e9a-4b91-b191-56d9281d5577.png)

**ndo2db service status:**
![image](https://user-images.githubusercontent.com/29793380/174206973-61ef8b7d-b5fc-4b60-a2b6-bc8fe23071f9.png)

**nagios service status**
![image](https://user-images.githubusercontent.com/29793380/174207076-0a1f6bc0-8f1e-486b-b3b4-818c4d437714.png)

Plugin (please complete the following information):

Version:
cacti 1.2.21
centos 7.9
php 7.3.33
mariadb 10.4.25
nagios 4.4.6
apache 20120211
json version 1.7.0
ndoutils 2.1.3
Source: [https://github.com/Cacti/plugin_npc/]
Browser:
Chrome [Version 101.0.4951.54 (Official Build) (64-bit)]
firefox Version 100.0.2
opera Version:86.0.4363.59

**Comment by TheWitness** [comment]
Is your cacti log clean?  I don't know much about this plugin, I only brought it to the 1.2.x framework.

**Comment by hinchoi** [comment]
issue has been solved after added the following column:

ALTER TABLE `npc_services` ADD COLUMN `importance` smallint(6) NOT NULL default 0 AFTER `icon_image_alt`;
ALTER TABLE `npc_hosts` ADD COLUMN `importance` smallint(6) NOT NULL default 0 AFTER `z_3d`;
ALTER TABLE `npc_contacts` ADD COLUMN `minimum_importance` smallint(6) NOT NULL default 0 AFTER `notify_host_downtime`;

![image](https://user-images.githubusercontent.com/29793380/174982779-05ad901f-5093-4ad9-a248-332056852cc2.png)

**Comment by TheWitness** [comment]
What version of Nagios where these columns introduced?  Can you research this for us?

**Comment by TheWitness** [comment]
Re-opening.  Need that Nagios version to update the documentation.

**Comment by hinchoi** [comment]
> What version of Nagios where these columns introduced? Can you research this for us?

https://forums.cacti.net/viewtopic.php?t=26540&start=435

**Comment by hinchoi** [comment]
Hi,

The issue was partially solved actually. the host up detail didnot show after click on "Up" host as following. Do you have any comment or idea for this? thanks.

![image](https://user-images.githubusercontent.com/29793380/175896152-2127f00c-b885-47a5-9d0c-bc6f4b0329d7.png)

**Comment by hinchoi** [comment]
solved after **reinstalled ** the plugin.
