### ISSUE TITLE
Errors after installation

### ISSUE THREAD

**Issue by boluser** [Cacti/plugin_npc#4]
I have installed the plugin in the following environment:
Linux: Ubuntu 18.01 LST
Apache 2.4.29
MySQL 5.7.25-0ubuntu0.18.04.2
PHP 7.2.10-0ubuntu0.18.04.1
Nagios Core 4.4.3
Cacti 1.2.1
ndoutils 2.1.3

3 types of errors appear:
Type1:
NPC DEBUG [NpcHostgroupsController] (getHostgroupServiceStatus) - Script execution time: 0.08 seconds
NPC DEBUG [NpcServicegroupsController] (getServicegroups) - Method execution time: 0.00 seconds
NPC DEBUG [NpcServicegroupsController] (getServicegroupServiceStatus) - Method execution time: 0.00 seconds
NPC DEBUG [NpcServicegroupsController] (getServicegroupServiceStatus) - Script execution time: 0.01 seconds
NPC DEBUG [NpcHostgroupsController] (getHostgroupHostStatus) - Script execution time: 0.01 seconds
NPC DEBUG [NpcServicegroupsController] (getHostStatusPortlet) - Method execution time: 0.00 seconds
NPC DEBUG [NpcServicegroupsController] (getHostStatusPortlet) - Script execution time: 0.00 seconds
NPC DEBUG [NpcHostsController] (summary) - Script execution time: 0.00 seconds
NPC DEBUG [NpcServicesController] (summary) - Script execution time: 0.00 seconds
NPC DEBUG [NpcNagiosController] (getProgramStatus) - Script execution time: 0.00 seconds
NPC DEBUG [NpcHostsController] (getHosts) - Script execution time: 0.01 seconds
NPC DEBUG [NpcServicesController] (getServices) - Script execution time: 0.01 seconds

Type2:
ERROR PHP DEPRECATED in  Plugin 'npc': Non-static method NpcServicesController::getServiceStatesByHost() should not be called statically in file: /opt/cacti/plugins/npc/controllers/hostgroups.php  on line: 271

Type3:
CMDPHP PHP ERROR Backtrace:  (/plugins/npc/npc.php[83]:NpcHostgroupsController->getHostgroupServiceStatus(),/plugins/npc/controllers/hostgroups.php[119]:NpcHostgroupsController->getHostgroupMemberServiceStatus(), /plugins/npc/controllers/hostgroups.php[271]:CactiErrorHandler())

I also have an open incidence on:
https://forums.cacti.net/viewtopic.php?f=14&t=59455

Thank you very much and greetings!!

**Comment by netniV** [comment]
Type 1 - Not an error, it's debug info
Type 2 - Now corrected
Type 3 - You've not actually given the error and it looks OK at the moment.

**Comment by boluser** [comment]
First, sorry for exposing my problem badly. My only intention is to help the plugin work.
I have updated the plugin. This is what appears in the log

CMDPHP  PHP ERROR Backtrace:   (/plugins/npc/npc.php[83]:NpcSyncController->listHostgroups(),  /plugins/npc/controllers/sync.php[159]:CactiErrorHandler())

ERROR PHP DEPRECATED in  Plugin 'npc':  Non-static method NpcCactiController::isMapped() should not be called  statically in file: /opt/cacti/plugins/npc/controllers/sync.php  on  line: 159

I hope it helps. Thank you so much for everything!

**Comment by netniV** [comment]
That should now be resolved.
