### ISSUE TITLE
CMDPHP PHP ERROR NOTICE Backtrace & ERROR PHP NOTICE in Plugin 'npc'

### ISSUE THREAD

**Issue by zhouleon** [Cacti/plugin_npc#6]
Version Info: 
Linux: Ubuntu 18.02 LST
Apache 2.4.29
MySQL 5.7.25-0ubuntu0.18.04.2
PHP 7.2.10-0ubuntu0.18.04.1
Nagios Core  4.4.3
Cacti 1.2.1
ndoutils 2.1.3

I just try updated version today, still has problem, here is the error message after install:

```
		2019.07.15 16:52:09 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/npc/npc.php[83]:NpcNagiosController->getProgramStatus(), /plugins/npc/controllers/nagios.php[42]:NpcNagiosController->processInfo(), /plugins/npc/controllers/nagios.php[109]:CactiErrorHandler())
		2019.07.15 16:52:09 - ERROR PHP NOTICE in Plugin 'npc': Undefined offset: 0 in file: /usr/share/cacti/site/plugins/npc/controllers/nagios.php on line: 109
		2019.07.15 16:51:09 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/npc/npc.php[83]:NpcNagiosController->getProgramStatus(), /plugins/npc/controllers/nagios.php[42]:NpcNagiosController->processInfo(), /plugins/npc/controllers/nagios.php[109]:CactiErrorHandler())
		2019.07.15 16:51:09 - ERROR PHP NOTICE in Plugin 'npc': Undefined offset: 0 in file: /usr/share/cacti/site/plugins/npc/controllers/nagios.php on line: 109
		2019.07.15 16:50:16 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/npc/npc.php[83]:NpcHostgroupsController->getOverview(), /plugins/npc/controllers/hostgroups.php[188]:CactiErrorHandler())
		2019.07.15 16:50:16 - ERROR PHP WARNING in Plugin 'npc': Invalid argument supplied for foreach() in file: /usr/share/cacti/site/plugins/npc/controllers/hostgroups.php on line: 188
		2019.07.15 16:50:16 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/npc/npc.php[83]:NpcHostgroupsController->getOverview(), /plugins/npc/controllers/hostgroups.php[188]:CactiErrorHandler())
		2019.07.15 16:50:16 - ERROR PHP NOTICE in Plugin 'npc': Undefined variable: temp in file: /usr/share/cacti/site/plugins/npc/controllers/hostgroups.php on line: 188
		2019.07.15 16:50:08 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/npc/npc.php[83]:NpcNagiosController->getProgramStatus(), /plugins/npc/controllers/nagios.php[42]:NpcNagiosController->processInfo(), /plugins/npc/controllers/nagios.php[109]:CactiErrorHandler())
		2019.07.15 16:50:08 - ERROR PHP NOTICE in Plugin 'npc': Undefined offset: 0 in file: /usr/share/cacti/site/plugins/npc/controllers/nagios.php on line: 109
```
Thanks!

**Comment by TheWitness** [comment]
Any update?  Have you fixed this?  Pull request?

**Comment by zhouleon** [comment]
Fixed, thanks!

**Comment by sunman2** [comment]
How did you resolve these issue i am facing same issues also please help me to resolve these as well thanks

Ubuntu 20.04.5 LTS
mysql> select VERSION();
+-------------------------+
| VERSION()               |
+-------------------------+
| 8.0.36-0ubuntu0.20.04.1 |

PHP-7.4
2024-05-30 20:26:29 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/npc/npc.php[83]:NpcNagiosController->getProgramStatus(), /plugins/npc/controllers/nagios.php[42]:NpcNagiosController->processInfo(), /plugins/npc/controllers/nagios.php[109]:CactiErrorHandler())
--
2024-05-30 20:26:29 - ERROR PHP NOTICE in Plugin 'npc': Trying to access array offset on value of type null in file: /var/www/html/cacti/plugins/npc/controllers/nagios.php on line: 109
2024-05-30 20:26:29 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/npc/npc.php[83]:NpcNagiosController->getProgramStatus(), /plugins/npc/controllers/nagios.php[42]:NpcNagiosController->processInfo(), /plugins/npc/controllers/nagios.php[109]:CactiErrorHandler())
2024-05-30 20:26:29 - ERROR PHP NOTICE in Plugin 'npc': Undefined offset: 0 in file: /var/www/html/cacti/plugins/npc/controllers/nagios.php on line: 109
