### ISSUE TITLE
Undefined index: value in file: /usr/share/cacti/site/plugins/npc/controllers/settings.php on line: 44

### ISSUE THREAD

**Issue by zhouleon** [Cacti/plugin_npc#8]
**Describe the bug**
Can not save portlet configuration

**To Reproduce**
1. Go to 'NPC'
2. Click on any portlet configuration, change Display Height and save
3. See error

Log:
2019/12/04 11:00:56 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/npc/npc.php[83]:NpcSettingsController->save(), /plugins/npc/controllers/settings.php[44]:CactiErrorHandler())
2019/12/04 11:00:56 - ERROR PHP NOTICE in Plugin 'npc': Undefined index: **value** in file: /usr/share/cacti/site/plugins/npc/controllers/settings.php on line: 44

2019/12/04 11:00:56 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/npc/npc.php[83]:NpcSettingsController->save(), /plugins/npc/controllers/settings.php[44]:CactiErrorHandler())
2019/12/04 11:00:56 - ERROR PHP NOTICE in Plugin 'npc': Undefined index: **name** in file: /usr/share/cacti/site/plugins/npc/controllers/settings.php on line: 44

**Comment by TheWitness** [comment]
Fixed.
